//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Box.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Box extends Thing implements Moveable{
	
	
	public void Destroy() {
	}
	
	public boolean Move(Direction dir) {
	}
	
	public boolean HitBy(Direction dir, Box b) {
	}
	
	public boolean HitBy(Direction dir, Worker w) {
	}
	
	public void CheckStucked(Direction d) {
	}
}
