//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Switch.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Switch extends Field {
	
	private Pit pit;
	
	public boolean HitBy(Direction dir, Worker w) {
	}
	
	public boolean HitBy(Direction dir, Box b) {
	}
}
