//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Field.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public abstract class Field {
	
	private Thing thing;
	private Warehouse warehouse;
	private Field neighbor;

	
	
	
	public void Add(Thing t) {
	}

	public void Remove(Thing t) {
	}
	
	public Field GetNeighbour(Direction dir) {
		return neighbor;
	}
	
	public boolean HitBy(Direction dir, Thing t) {
		return true;
	}
	
	public Thing GetThing() {
		return thing;
	}
}
