package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Floor.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Mezõ típusú egyszerû padló osztály */
public class Floor extends Field {
	
	/* Dolog adott irányba rá szeretne lépni.
	 * Meghívja a dologra az ütköztetõ függvényt, majd igazat ad vissza. 
	 */
	public boolean HitBy(Direction dir, Thing t) {
		if(GetThing() != null)
			return GetThing().HitBy(dir, t);
		return true;
	}
}
