//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Floor.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Floor extends Field {
	
	public boolean HitBy(Direction dir, Thing t) {
		return true;
	}
}
