package GameLogic;

import Utility.FunctionLogger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Grinder.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Grinder extends Field {
	
	
	private Worker player;
	
	public void SetPlayer(Worker p) {
		FunctionLogger.logFunctionCalled(toString(), "SetPlayer(Worker p)");
		player = p;
		FunctionLogger.logFunctionReturnVoid();
	}
	
	public Worker GetPlayer() {
		FunctionLogger.logFunctionCalled(toString(), "GetPlayer()");
		return FunctionLogger.logFunctionReturn( player );
	}

	
	public boolean HitBy(Direction dir, Box b) {
		FunctionLogger.logFunctionCalled(toString(), "HitBy(Direction dir, Box b)");
		if(GetThing() != null)
			if(GetThing().HitBy(dir, b)) {
				this.player.AddPoint();
				b.Destroy();
				return FunctionLogger.logFunctionReturn( true );
			}
			else
				return FunctionLogger.logFunctionReturn( false );
		else
			return FunctionLogger.logFunctionReturn( true );
	}
	
	public boolean HitBy(Direction dir, Worker w) {
		FunctionLogger.logFunctionCalled(toString(), "HitBy(Direction dir, Worker w)");
		if(GetThing() != null)
			return FunctionLogger.logFunctionReturn( GetThing().HitBy(dir, w) );
		return FunctionLogger.logFunctionReturn( true );
	}
}
