package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Grinder.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Grinder extends Field {
	
	
	private Worker player;
	
	public void SetPlayer(Worker p) {
		player = p;
	}
	
	public Worker GetPlayer() {
		return player;
	}

	
	public boolean HitBy(Direction dir, Box b) {
		if(GetThing() != null)
			if(GetThing().HitBy(dir, b)) {
				this.player.AddPoint();
				b.Destroy();
				return true;
			}
			else
				return false;
		else
			return true;
	}
	
	public boolean HitBy(Direction dir, Worker w) {
		if(GetThing() != null)
			return GetThing().HitBy(dir, w);
		return true;
	}
}
