//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Grinder.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Grinder extends Field {
	
	private Worker player;
	
	public boolean HitBy(Direction dir, Box b) {
		return true;
	}
	
	public boolean HitBy(Direction dir, Worker w) {
		return true;
	}
}
