package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab	
//  @ File Name : Moveable.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Mozgatható dolgokat (doboz, munkás) reprezentáló interfész */
public interface Moveable {
	
	public boolean Move(Direction dir);
}
