//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Pit.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Pit extends Field {

	private boolean open;
	
	public boolean HitBy(Direction dir, Worker w) {
		return true;
	}
	
	public boolean HitBy(Direction dir, Box b) {
		return true;
	}

	public void SetOpen(boolean b) {
	}
	
	public boolean isOpen() {
		return true;
	}
}
