package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Pit.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Mezõ típusú lyuk.
 * Tárolja, hogy nyitott vagy csukott állapotban van e. 
 */
public class Pit extends Field {

	private boolean open;
	
	/* Nyitottsági állapot beállítása */
	public void SetOpen(boolean b) {
		open = b;
	}
	
	/* Nyitottsági állapot lekérdezése */
	public boolean isOpen() {
		return open;
	}
	
	/* Lyuknak adott irányba munkás ütközik.
	 * Ha van rajta dolog ütközteti vele. Ha ráléphet és
	 * nyitva van, megöli a játékost. 
	 */
	public boolean HitBy(Direction dir, Worker w) {
		if(GetThing() != null)
			if(GetThing().HitBy(dir, w))
				if(open) {
					w.Die();
					return true;
				}
				else
					return true;
			else
				return false;
		else
			return true;
	}
	
	/* Lyuknak adott irányba doboz ütközik.
	 * Ha van rajta dolog ütközteti vele. Ha ráléphet és
	 * nyitva van, elpusztítja a dobozt. 
	 */
	public boolean HitBy(Direction dir, Box b) {
		if(GetThing() != null)
			if(GetThing().HitBy(dir, b))
				if(open) {
					b.Destroy();;
					return true;
				}
				else
					return true;
			else
				return false;
		else
			return true;
	}
}
