package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Switch.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Mezõ típusú kapcsoló.
 * Tárolja a hozzá tartozó lyukat.  
 */
public class Switch extends Field {
	
	private Pit pit;
	
	/* Lyuk beállítása */
	public void SetPit(Pit p) {
		pit = p;
	}
	
	/* Lyuk lekérdezése */
	public Pit GetPit() {
		return pit;
	}
	
	/* Kapcsolónak adott irányba munkás ütközik.
	 * Ha van rajta valami ütközteti vele. Ha ráléphet bezárja
	 * a hozzá tartozó lyukat.
	 */
	public boolean HitBy(Direction dir, Worker w) {
		if(GetThing() != null)
			if(GetThing().HitBy(dir, w)) {
					pit.SetOpen(false);;
					return true;
			}
			else
				return false;
		else
			return true;	
	}
	
	/* Kapcsolónak adott irányba doboz ütközik.
	 * Ha van rajta valami ütközteti vele. Ha ráléphet kinyitja
	 * a hozzá tartozó lyukat.
	 */
	public boolean HitBy(Direction dir, Box b) {
		if(GetThing() != null)
			if(GetThing().HitBy(dir, b)) {
					pit.SetOpen(true);;
					return true;
			}
			else
				return false;
		else
			return true;
	}
}
