//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Thing.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public abstract class Thing {

	private boolean stucked;
	private Field field;
	
	public void HitBy(Direction dir, Thing t) {
	}
	
	public Field GetField() {
		return field;
	}
	
	public boolean isStucked() {
		return true;
	}
	
	public void setStucked(boolean b) {
	}
}
