package GameLogic;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Thing.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public abstract class Thing {

	private boolean stucked;
	private Field field;

	public enum Direction {
		Up,
		Down,
		Left,
		Right;
	}
	
	public void HitBy(Direction dir, Thing t) {
	}
	
	public Field GetField() {
	}
	
	public boolean isStucked() {
	}
	
	public void setStucked(boolean b) {
	}
}
