package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Thing.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Mezõn lévõ dolgokat reprezentálja.
 * Tárolja, hogy be vannak-e ragadva és a mezõt
 * amin a dolog áll.
 */
public abstract class Thing {

	private boolean stucked;
	private Field field;

	/* Dolog mezõjének beállítása */
	public void SetField(Field f) {
		field = f;
	}
	
	/* Dolog mezõjének lekérdezése. */
	public Field GetField() {
		return field;
	}
	
	/* Dolog beragadottságának beállítása */
	public void SetStucked(boolean b) {
		stucked = b;
	}
	
	/* Dolog beragadottságának lekérdezése. */
	public boolean isStucked() {
		return stucked;
	}
	
	/* Dolognak adott irányból egy másik dolog ütközik.
	 * Alapból igazt ad vissza. 
	 */
	public boolean HitBy(Direction dir, Thing t) { 
		return true;
	}
}
