package GameLogic;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Wall.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Dologból típusú fal */
public class Wall extends Thing {

	/* Falnak adott irányba munkás megy.
	 * Hamist ad vissza.
	 */
	public boolean HitBy(Direction dir, Worker w) {
		return false;
	}
	
	/* Falnak adott irányba doboz megy.
	 * Hamist ad vissza.
	 */
	public boolean HitBy(Direction dir, Box b) {
		b.CheckStucked(dir);
		return false;
	}
}
