package GameLogic;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Wall.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Wall extends Thing {

	public boolean HitBy(Direction dir, Worker w) {
	}
	
	public boolean HitBy(Direction dir, Box b) {
	}
}
