package GameLogic;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Warehouse.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//



/* Raktár
 * Tárolja a játékosok számát, pályát alkotó mezõket, 
 * és a pályán lévõ dobozokat. 
 */
public class Warehouse {

	private int workerNumber = 1;
	private ArrayList<Field> fields;
	private ArrayList<Box> boxes;
	
	/* Munkásszám beállítása */
	public void SetWorkerNumber(int n) {
		workerNumber = n;
	}
	
	/* Mezõk listájának beállítása */
	public void SetFields(ArrayList<Field> f) {
		fields = f;
	}
	
	/* Dobozok listájának beállítása */
	public void SetBoxes(ArrayList<Box> b) {
		boxes = b;
	}
	
	/* Munkások számának lekérdezése */
	public int GetWorkerNumber() {
		return workerNumber;
	}
	
	/* Dobozlista lekérdezése */
	public ArrayList<Box> GetBoxes(){
		return boxes;
	}
	
	/* Mezõlista lekérdezése */
	public ArrayList<Field> GetFields(){
		return fields;
	}
	
	/* Adott doboz a dobozlistából törlése */
	public void RemoveBox(Box b) {
		boxes.remove(b);
	}
	
	/* Raktár iniciálizálása */
	public void Initialize() {
	}
	
	/* Játék végének ellenõrzése. 
	 * Ha elfogytak a munkások vagy a dobozok, vagy
	 * minden doboz beragadt akkor vége a játéknak. 
	 */
	public void CheckEndGame() {
		if(workerNumber == 0)
			EndGame();
		
		if(boxes.isEmpty())
			EndGame();
		
		for(Box b : boxes)
			if(!b.isStucked())
				return;
		
		EndGame();
	}
	
	/* Játék vége */
	public void EndGame() {
	}
	
}
