//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 6projlab
//  @ File Name : Warehouse.java
//  @ Date : 2018.03.17.
//  @ Author : Gyöngyösi Péter
//
//




public class Warehouse {

	private int workerNumber;
	private Field[] fields;
	private Box[] boxes;
	
	public void Initialize() {
	}
	
	public void RemoveBox(Box b) {
	}
	
	public void CheckEndGame() {
	}
	
	public void EndGame() {
	}
	
	public void SetWorkerNumber(int n) {
	}
	
	public int GetWorkerNumber() {
		return workerNumber;
	}
}
